name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
        if [ -f web/requirements.txt ]; then pip install -r web/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pylint --max-line-length=128 $(git ls-files '*.py')
        pylint --disable=too-few-public-methods web/tests
        pylint --disable=too-many-arguments,too-many-positional-arguments $(git ls-files -- '*.py')
        TEST_FILES="$(git ls-files -- 'tests/**/*.py' 'api/tests/**/*.py' 'web/tests/**/*.py' || true)"
        if [ -n "$TEST_FILES" ]; then
          pylint --rcfile=.pylintrc --disable=too-few-public-methods $TEST_FILES
          pylint --disable=no-member $TEST_FILES
        else
          echo "No test files found."
        fi
