name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f api/requirements.txt ]; then pip install -r api/requirements.txt; fi
          if [ -f web/requirements.txt ]; then pip install -r web/requirements.txt; fi

      - name: Lint app code (strict)
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          APP_FILES="$(git ls-files -- '*.py' | grep -vE '(^|/)tests/')" || true
          if [ -n "$APP_FILES" ]; then
            pylint --max-line-length=128 \
                   --disable=too-many-arguments,too-many-positional-arguments \
                   $APP_FILES
          else
            echo "No app files to lint."
          fi

      - name: Lint tests (relaxed)
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          TEST_FILES="$(git ls-files -- 'tests/**/*.py' 'tests/*.py' 'api/tests/**/*.py' 'api/tests/*.py' 'web/tests/**/*.py' 'web/tests/*.py')" || true
          if [ -n "$TEST_FILES" ]; then
            pylint --max-line-length=128 \
                   --disable=no-member,too-few-public-methods \
                   $TEST_FILES
          else
            echo "No test files found."
          fi
